name: Create Release

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Semver type of new version (major / minor / patch)'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # This checks out your repository onto the runner, allowing you to run scripts or other actions against your code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.name 'Aeina9'
          git config user.email 'ixamynguyen@gmail.com'

      - name: Bump Version
        run: npm version ${{ github.event.inputs.version }}

      - name: Push latest version
        run: git push origin main --follow-tags

      - name: Create Release
        run: gh release create ${{ github.ref_name }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}